version: '3.4'
services:
  pgdb:
    image: postgres:latest
    environment:
      POSTGRES_DB: "django_db"
      POSTGRES_USER: "django"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"

  web:
    image: pjjj
    command: sh -c "
      sleep 10 &&
      echo 123 &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000 "
    ports:
      - "8000:8000"
    links:
      - "pgdb:database"
    depends_on:
     - pgdb

