# Generated by Django 4.0.2 on 2022-03-17 10:38

from django.db import migrations, models
import photojournal.models


class Migration(migrations.Migration):

    dependencies = [
        ('photojournal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dateBirthday',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstName',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='secondName',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userPhoto',
            field=models.FileField(blank=True, upload_to=photojournal.models.user_path),
        ),
    ]
