# Generated by Django 4.0.2 on 2022-04-19 08:13

from django.db import migrations, models
import photojournal.models


class Migration(migrations.Migration):

    dependencies = [
        ('photojournal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='creation',
            field=models.DateTimeField(auto_now=True, verbose_name='Date create'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=models.ImageField(upload_to=photojournal.models.photo_path, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='photoPublish',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=40, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='creation',
            field=models.DateTimeField(auto_now=True, verbose_name='date create'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(max_length=100, verbose_name='text'),
        ),
    ]
