# Generated by Django 4.0.2 on 2022-03-17 10:50

from django.db import migrations, models
import photojournal.models


class Migration(migrations.Migration):

    dependencies = [
        ('photojournal', '0002_alter_profile_datebirthday_alter_profile_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dateBirthday',
            field=models.DateTimeField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstName',
            field=models.TextField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='secondName',
            field=models.TextField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userPhoto',
            field=models.FileField(blank=True, default='', upload_to=photojournal.models.user_path),
        ),
    ]
