# Generated by Django 4.0.2 on 2022-03-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photojournal', '0003_alter_profile_datebirthday_alter_profile_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dateBirthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
