# Generated by Django 4.0.2 on 2022-03-17 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photojournal', '0004_alter_profile_datebirthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userProfile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
