# Generated by Django 4.0.2 on 2022-03-21 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import photojournal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photojournal', '0005_alter_profile_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='creation',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=models.ImageField(upload_to='photojournal/static/images/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='photoPublish',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photojournal.blog', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='creation',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(max_length=100, verbose_name='Коментарий'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dateBirthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emailProfile',
            field=models.EmailField(max_length=200, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstName',
            field=models.TextField(blank=True, default='', max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='secondName',
            field=models.TextField(blank=True, default='', max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userPhoto',
            field=models.FileField(blank=True, default='', upload_to=photojournal.models.user_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userProfile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
    ]
